const routes = {
  private: {
    internal: {
      clients: '/internal/clients',
      client: '/internal/client/',
      editClient: '/internal/edit-client/',
      newClient: '/internal/new-client',
      workers: '/internal/workers',
      worker: '/internal/worker/',
      newWorker: '/internal/new-worker',
      editWorker: '/internal/edit-worker/',
      stocks: '/internal/stocks',
      stock: '/internal/stock/',
      editStock: '/internal/edit-stock/',
      newStock: '/internal/new-stock',
      similarProjects: '/internal/projects-similar',
      projects: '/internal/projects',
      project: '/internal/project/',
      budget: '/internal/budget/',
      editBudget: '/internal/edit-budget/',
      newProject: '/internal/new-project',
      editProject: '/internal/edit-project/',
      messages: '/internal/messages',
      account: '/internal/account',
      error: '/404',
      packages: '/internal/packing',
      package: '/internal/project-packages/',
      newPackage: '/internal/new-package/',
      newLeftover: '/internal/new-leftover',
      dashboards: '/internal/dashboards',
      factorys: '/internal/factory',
      factory: '/internal/factory-ground/',
      assemblys: '/internal/assemblys',
      profiles: '/internal/profiles',
      profile: '/internal/profile/',
      editProfile: '/internal/edit-profile/',
      newProfile: '/internal/new-profile',
      machines: '/internal/machines',
      machine: '/internal/machine/',
      newMachine: '/internal/new-machine',
      editMachine: '/internal/edit-machine/',
    },
    //  Clients Pages
    terms: '/terms',
    privacy: '/privacy',
    tos: '/tos',
    projects: '/projects',
    project: '/project/',
    budget: '/budget/',
    account: '/account',
    messages: '/messages',
    error: '/404',
  },
  public: {
    signIn: '/',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    accountActivation: '/account-activation',
    signInInternal: '/signin',
    forgotPasswordInternal: '/forgotPassword',
    resetPasswordInternal: '/resetPassword',
  }
};

export default routes;
