export {
  MACHINES_REQUEST,
  MACHINES_FAIL,
  MACHINES_SUCCESS,
  NEW_MACHINE_REQUEST,
  NEW_MACHINE_FAIL,
  NEW_MACHINE_SUCCESS,
  UPDATE_MACHINE_REQUEST,
  UPDATE_MACHINE_FAIL,
  UPDATE_MACHINE_SUCCESS,
  machines,
  newMachine,
  machine,
  updateMachine,
  deleteMachine,
} from './machine';
