describe('Login', () => {
  it.only('passes', () => {
    cy.visit('http://localhost:3000/')
    // cy.get('#email').type('bruno.barros@nka.pt')
    // cy.get('#password').type('123456')
    cy.get('#submit').click()
    cy.get('#drawerToggleBtn').click()
    cy.get('#ordersSimilar').click()
    cy.get('#drawerToggleBtn').click()
    cy.get('#stocks').click()
    cy.get('#drawerToggleBtn').click()
    cy.get('#clients').click()
    cy.get('#drawerToggleBtn').click()
    cy.get('#workers').click()
    cy.get('#drawerToggleBtn').click()
    cy.get('#leftovers').click()
    cy.get('#drawerToggleBtn').click()
    cy.get('#dashboard').click()
  })
})
