export {
  PERMISSIONS_REQUEST,
  PERMISSIONS_FAIL,
  PERMISSIONS_SUCCESS,
  RESOURCES_REQUEST,
  RESOURCES_FAIL,
  RESOURCES_SUCCESS,
  NEW_PERMISSION_REQUEST,
  NEW_PERMISSION_FAIL,
  NEW_PERMISSION_SUCCESS,
  permissions,
  resources,
  newPermission,
} from './permission';
