import { Archive, Factory, MessageCircle, Network, PackageCheck, Scan, ShieldAlert, Table, Users } from 'lucide-react';
import React from 'react';
import routes from '../../navigation/routes';
import { Webhook } from '@mui/icons-material';

export const navLinks = [
  {
    title: 'Projetos',
    id: 'projectsInternal',
    url: routes.private.projects,
    icon: <Archive strokeWidth='1' size={20} />,
    allowed: 'projects',
    allowed_: 'access_projects',
  },
  {
    title: 'Projetos',
    id: 'projectsClient',
    url: routes.private.internal.projects,
    icon: <Archive strokeWidth='1' size={20} />,
    allowed: 'projects',
    allowed_: 'access_projects',
  },
  {
    title: 'Mensagens',
    id: 'messagesClient',
    url: routes.private.messages,
    icon: <MessageCircle strokeWidth='1' size={20} />,
    allowed: 'client',
    allowed_: 'access_messages',

  },
  {
    title: 'Projetos Similares',
    id: 'projectsSimilar',
    url: routes.private.internal.projectsSimilar,
    icon: <Archive strokeWidth='1' size={20} />,
    allowed: 'projects',
    allowed_: 'access_projects_similar',
    underline: true,
  },
  {
    title: 'Stock',
    id: 'stocks',
    url: routes.private.internal.stocks,
    icon: <Table strokeWidth='1' size={20} />,
    allowed: 'stocks',
    allowed_: 'access_stocks',
  },
  {
    title: 'Máquinas',
    id: 'machines',
    url: routes.private.internal.machines,
    icon: <Webhook strokeWidth='1' size={20} />,
    allowed: 'machines',
    allowed_: 'access_machine',
    underline: true,
  },
  {
    title: 'Chão de Fabrica',
    id: 'fabrica',
    url: routes.private.internal.factorys,
    icon: <Factory strokeWidth='1' size={20} />,
    allowed: 'factory',
    allowed_: 'access_factory',
  },
  {
    title: 'Montagens',
    id: 'assembly',
    url: routes.private.internal.assemblys,
    icon: <Network strokeWidth='1' size={20} />,
    allowed: 'assemblys',
    allowed_: 'access_assembly',
  },
  {
    title: 'Embalamentos',
    id: 'packing',
    url: routes.private.internal.packages,
    icon: <PackageCheck strokeWidth='1' size={20} />,
    allowed: 'packages',
    allowed_: 'access_packing',
  },
  {
    title: 'Sobrantes',
    id: 'leftovers',
    url: routes.private.internal.leftovers,
    icon: <Scan strokeWidth='1' size={20} />,
    allowed: 'leftovers',
    allowed_: 'access_leftovers',
    underline: true
  },
  {
    title: 'Clientes',
    id: 'clients',
    url: routes.private.internal.clients,
    icon: <Users strokeWidth='1' size={20} />,
    allowed: 'clients',
    allowed_: 'access_clients',
  },
  {
    title: 'Utilizadores',
    id: 'workers',
    url: routes.private.internal.workers,
    icon: <Users strokeWidth='1' size={20} />,
    allowed: 'workers',
    allowed_: 'access_workers',
  },
  {
    title: 'Perfis',
    id: 'profiles',
    url: routes.private.internal.profiles,
    icon: <ShieldAlert strokeWidth='1' size={20} />,
    allowed: 'dashboards',
    allowed_: 'access_profiles',
  },
];
