import { Webhook } from '@mui/icons-material';
import { Archive, Factory, MessageCircle, Network, PackageCheck, Scan, ShieldAlert, Table, Users } from 'lucide-react';
import React from 'react';
import routes from '../../navigation/routes';

export const navLinks = [
  {
    title: 'Projetos',
    id: 'projectsInternal',
    url: routes.private.projects,
    icon: <Archive strokeWidth='1' size={20} />,
    allowed: 'projects',
    allowed_: 'list_project',
  },
  {
    title: 'Projetos',
    id: 'projectsClient',
    url: routes.private.internal.projects,
    icon: <Archive strokeWidth='1' size={20} />,
    allowed: 'projects',
    allowed_: 'list_project',
  },
  {
    title: 'Mensagens',
    id: 'messagesClient',
    url: routes.private.messages,
    icon: <MessageCircle strokeWidth='1' size={20} />,
    allowed: 'client',
    allowed_: 'list_message',

  },
  {
    title: 'Projetos Similares',
    id: 'similarProjects',
    url: routes.private.internal.similarProjects,
    icon: <Archive strokeWidth='1' size={20} />,
    allowed: 'projects',
    allowed_: 'list_similarProject',
    underline: true,
  },
  {
    title: 'Stocks',
    id: 'stocks',
    url: routes.private.internal.stocks,
    icon: <Table strokeWidth='1' size={20} />,
    allowed: 'stocks',
    allowed_: 'list_stock',
  },
  {
    title: 'Máquinas',
    id: 'machines',
    url: routes.private.internal.machines,
    icon: <Webhook strokeWidth='1' fontSize={'small'} />,
    allowed: 'machines',
    allowed_: 'list_machine',
    underline: true,
  },
  {
    title: 'Chão de Fabrica',
    id: 'fabrica',
    url: routes.private.internal.factorys,
    icon: <Factory strokeWidth='1' size={20} />,
    allowed: 'factory',
    allowed_: 'list_factory',
  },
  {
    title: 'Montagens',
    id: 'assembly',
    url: routes.private.internal.assemblys,
    icon: <Network strokeWidth='1' size={20} />,
    allowed: 'assemblys',
    allowed_: 'list_assembly',
  },
  {
    title: 'Embalamentos',
    id: 'packing',
    url: routes.private.internal.packages,
    icon: <PackageCheck strokeWidth='1' size={20} />,
    allowed: 'packages',
    allowed_: 'list_package',
  },
  {
    title: 'Sobrantes',
    id: 'leftovers',
    url: routes.private.internal.newLeftover,
    icon: <Scan strokeWidth='1' size={20} />,
    allowed: 'leftovers',
    allowed_: 'create_leftover',
    underline: true
  },
  {
    title: 'Clientes',
    id: 'clients',
    url: routes.private.internal.clients,
    icon: <Users strokeWidth='1' size={20} />,
    allowed: 'clients',
    allowed_: 'list_owner',
  },
  {
    title: 'Utilizadores',
    id: 'workers',
    url: routes.private.internal.workers,
    icon: <Users strokeWidth='1' size={20} />,
    allowed: 'workers',
    allowed_: 'list_worker',
  },
  {
    title: 'Perfis',
    id: 'profiles',
    url: routes.private.internal.profiles,
    icon: <ShieldAlert strokeWidth='1' size={20} />,
    allowed: 'dashboards',
    allowed_: 'list_profile',
  },
];
