export {
  WORKERS_REQUEST,
  WORKERS_FAIL,
  WORKERS_SUCCESS,
  WORKER_REQUEST,
  WORKER_FAIL,
  WORKER_SUCCESS,
  ADD_WORKER_REQUEST,
  ADD_WORKER_SUCCESS,
  ADD_WORKER_FAIL,
  SET_DISPLAYED_WORKER,
  workers,
  worker,
  newWorker,
  setDisplayedWorker,
} from './worker';
