export {
  FURNITURES_REQUEST,
  FURNITURES_FAIL,
  FURNITURES_SUCCESS,
  NEW_FURNITURE_REQUEST,
  NEW_FURNITURE_FAIL,
  NEW_FURNITURE_SUCCESS,
  UPDATE_FURNITURE_REQUEST,
  UPDATE_FURNITURE_FAIL,
  UPDATE_FURNITURE_SUCCESS,
  furnitures,
  furniture,
  newFurniture,
  updateFurniture,
  deleteFurniture,
} from './furniture';
